from pygame import Color

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

FRAME_RATE = 60

BACKGROUND_COLOR = Color(0, 0, 0)  # Black

ASTEROID_COLOR = Color(255, 255, 255)  # White
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_COLOR = Color(255, 255, 0)  # Yellow
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3  # seconds

SHOT_COLOR = Color(255, 0, 0)  # Red
SHOT_RADIUS = 5